server:
 port: 9190
 
spring:
  application:
    name: tour-eureka-server
 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9190/eureka/}